name: Measure Lead Time

on:
  workflow_run:
    workflows: ["Node.js CI", "Deploy to Vercel"]
    types:
      - completed

jobs:
  record-time:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Record Time
        run: |
          echo "Workflow '${{ github.event.workflow_run.name }}' completed at ${{ github.event.workflow_run.updated_at }}"
          # Aqui você pode adicionar lógica para calcular e armazenar o tempo de lead
          # Por exemplo, enviar esses dados para um serviço externo ou armazenar em um arquivo